### PR TITLE
[CA - TVA] fix replay

### PR DESCRIPTION
**Pull request by darodi**
[CA - TVA] fix replay

draft: I don't have a VPN to test

### CODE REVIEW

**Comment by darodi** [comment]
@joaopa00 

Je n'ai pas de VPN pour tester. Il faudrait vérifier avant merge.

**Comment by joaopa00** [comment]
Avec les feux de l'amour, je reçois "Tom many redirects Exceeded 30 redirects"

**Comment by JustBeta** [comment]
if you want, I'm create a vpn relay for test.
if you want desire access this, contact me in private for you send information.
I don't know the private transfer possibility. my vpn relais is Wireguard.

**Comment by joaopa00** [comment]
C'est un problème de Curl. 
Sous linux, Curl est incapable de récupérer le site  https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239
Par contre wget y arrive

**Comment by darodi** [comment]
on dirait qu'il faut se loguer sur le site?

```
2022-09-13 19:07:43 [info] [xbmc] [debug level] [urllib3.connectionpool] https://www.qub.ca:443 "GET /tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10524-1079986838 HTTP/1.1" 307 0
2022-09-13 19:07:43 [info] [xbmc] [debug level] [urlquick] Caching 307 Temporary Redirect response
2022-09-13 19:07:44 [info] [xbmc] [debug level] [urllib3.connectionpool] https://www.qub.ca:443 "GET /connexion?isSilentAuth=true&next=/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10524-1079986838 HTTP/1.1" 302 288
2022-09-13 19:07:44 [info] [xbmc] [debug level] [urlquick] Caching 302 Moved Temporarily response
2022-09-13 19:07:44 [info] [xbmc] [debug level] [urllib3.connectionpool] Starting new HTTPS connection (1): connect.qub.ca:443
2022-09-13 19:07:44 [info] [xbmc] [debug level] [urllib3.connectionpool] https://connect.qub.ca:443 "GET /authorize?client_id=4s2s2vl04topmjb9g2dvllbavm&identification=false&prompt=none&redirect_uri=https%3A%2F%2Fwww.qub.ca%2Fconnect-callback&response_type=code&scope=openid&state=77525d5c-0197-4ad1-afb0-8d0749ee34ff&theme=QUB&tracking_object=%7B%22brand%22%3A%22QUB%22%2C%22app%22%3A%7B%22platform%22%3A%22web%22%7D%7D HTTP/1.1" 302 20
2022-09-13 19:07:44 [info] [xbmc] [debug level] [urlquick] Caching 302 Moved Temporarily response
2022-09-13 19:07:44 [info] [xbmc] [debug level] [urllib3.connectionpool] https://www.qub.ca:443 "GET /connect-callback?error=login_required&state=77525d5c-0197-4ad1-afb0-8d0749ee34ff HTTP/1.1" 302 115
```

**Comment by joaopa00** [comment]
Je ne pense pas. Avec wget
wget  'https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239' -v
--2022-09-13 07:27:11--  https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239
Resolving www.qub.ca (www.qub.ca)... 104.98.117.16, 104.98.117.19
Connecting to www.qub.ca (www.qub.ca)|104.98.117.16|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://www.qub.ca/connexion?isSilentAuth=true&next=/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239 [following]
--2022-09-13 07:27:11--  https://www.qub.ca/connexion?isSilentAuth=true&next=/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239
Reusing existing connection to www.qub.ca:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://connect.qub.ca/authorize?client_id=4s2s2vl04topmjb9g2dvllbavm&identification=false&prompt=none&redirect_uri=https%3A%2F%2Fwww.qub.ca%2Fconnect-callback&response_type=code&scope=openid&state=6f52a28a-561d-4cab-975c-e23776686e95&theme=QUB&tracking_object=%7B%22brand%22%3A%22QUB%22%2C%22app%22%3A%7B%22platform%22%3A%22web%22%7D%7D [following]
--2022-09-13 07:27:12--  https://connect.qub.ca/authorize?client_id=4s2s2vl04topmjb9g2dvllbavm&identification=false&prompt=none&redirect_uri=https%3A%2F%2Fwww.qub.ca%2Fconnect-callback&response_type=code&scope=openid&state=6f52a28a-561d-4cab-975c-e23776686e95&theme=QUB&tracking_object=%7B%22brand%22%3A%22QUB%22%2C%22app%22%3A%7B%22platform%22%3A%22web%22%7D%7D
Resolving connect.qub.ca (connect.qub.ca)... 104.98.117.19, 104.98.117.16
Connecting to connect.qub.ca (connect.qub.ca)|104.98.117.19|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.qub.ca/connect-callback?error=login_required&state=6f52a28a-561d-4cab-975c-e23776686e95 [following]
--2022-09-13 07:27:13--  https://www.qub.ca/connect-callback?error=login_required&state=6f52a28a-561d-4cab-975c-e23776686e95
Connecting to www.qub.ca (www.qub.ca)|104.98.117.16|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: /tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239 [following]
--2022-09-13 07:27:14--  https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239
Reusing existing connection to www.qub.ca:443.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://api.qub.ca/anonymous-id/redirect?next=https%3a%2f%2fwww.qub.ca%2ftvaplus%2ftva%2fles-feux-de-l-amour%2fsaison-17%2fepisode-10519-1079557239%3f [following]
--2022-09-13 07:27:14--  https://api.qub.ca/anonymous-id/redirect?next=https%3a%2f%2fwww.qub.ca%2ftvaplus%2ftva%2fles-feux-de-l-amour%2fsaison-17%2fepisode-10519-1079557239%3f
Resolving api.qub.ca (api.qub.ca)... 65.8.158.89, 65.8.158.114, 65.8.158.2, ...
Connecting to api.qub.ca (api.qub.ca)|65.8.158.89|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.qub.ca/api/anonymous-id/redirect/callback?qub_anonymous_id=88405f6f-479e-4b57-a318-ccc65775482f&next=https%3A%2F%2Fwww.qub.ca%2Ftvaplus%2Ftva%2Fles-feux-de-l-amour%2Fsaison-17%2Fepisode-10519-1079557239%3F [following]
--2022-09-13 07:27:15--  https://www.qub.ca/api/anonymous-id/redirect/callback?qub_anonymous_id=88405f6f-479e-4b57-a318-ccc65775482f&next=https%3A%2F%2Fwww.qub.ca%2Ftvaplus%2Ftva%2Fles-feux-de-l-amour%2Fsaison-17%2Fepisode-10519-1079557239%3F
Connecting to www.qub.ca (www.qub.ca)|104.98.117.16|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239 [following]
--2022-09-13 07:27:16--  https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239
Reusing existing connection to www.qub.ca:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘episode-10519-1079557239.1’

episode-10519-1079     [  <=>            ]  75,52K   257KB/s    in 0,3s    

2022-09-13 07:27:17 (257 KB/s) - ‘episode-10519-1079557239.1’ saved [77336]

**Comment by darodi** [comment]
Dans le browser, on a 7 redirect.
Je vais les appeler à la main avec des `allow_redirects=False` pour voir ce que ça donne
` resp = urlquick.get(URL_INFO_STREAM % video_slug, headers=headers, allow_redirects=False)`

**Comment by joaopa00** [comment]
La commande  curl -b log.txt  -c log.txt 'https://www.qub.ca/tvaplus/tva/les-feux-de-l-amour/saison-17/episode-10519-1079557239' -v -L --output site.txt 
fonctionne pour récupérer le site

**Comment by darodi** [comment]
j'ai force pushed
ça marche même sans VPN 🎉

**Comment by darodi** [comment]
- fix  #945

**Pull request merged**
