### PR TITLE
Gaet81 patch 1

### PR DESCRIPTION
**Pull request by Gaet81**
Hi,

I've added Mont Blanc Live TV & 8 Mont-Blanc (both Live and Replay).
These are real tv channels but on the web it's hosted by Dailymotion, so I've created a dailymotion.py in channel.
Basically you can really easily add any channel that broadcast on Dailymotion. You just need the username for the channel and it should work.

Please let me know if you are experiencing any issue.

Regards,

Gaet81

### CODE REVIEW

**Comment by wwark** [comment]
Hi @Gaet81,

Thank you for this PR !

I think it will be better to pass by the website (https://montblanclive.com/mblivetv/replay or http://8montblanc.fr/replay-categorie/economie-social-replay/) and not used directly the dailymotion api.
for classing videos by category.

exemple of http://8montblanc.fr:
.....
Economie Et Sociale =>
=>Ambition (Put videos)
=>Solidarité (Put videos)
=> .....
Sport et Montagne =>
...

Can you please create two files for each channel and try to add category for each channel?
If it is to difficult I can help !

You can follow this file (might help)
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/fr/nouvellesecritures.py

Wwark

**Comment by Gaet81** [comment]
Hi Wwark,

I understand your point for big channels, but here it's a small channel with really limited number of programs.
I just added the replay because it was easy to do.
If there was json I would agree that I should go via the website, but scrapping the website is not a best practice because it's not sustainable and need a lot of maintenance .
If you want I can add a search function in the replay so that the user can search on keywords but I'll not scrap the website.

Regards,
Gaetan

**Comment by wwark** [comment]
Hi @Gaet81,

The channel replay website don't change too much (1 time a year and some channel works since the first time without change related to the scrapping) and we have a tool (https://github.com/Catch-up-TV-and-More/catchuptvandmore-test) to check automatically if there is some changes. 
Every channel pass firstly by a call to the website of the channel and we used resolver_proxy.py at the end when we have video_id of Youtube, Dailymotion,
And it is not a problem for me to fix after if the channel not work in the future.

@SylvainCecchetto, what do you think ?

I check again the code, is it possible to add the download mode ?
example:
item.context.script(
     get_video_url,
            plugin.localize(LABELS['Download']),
            item_id=item_id,
            video_url=video_url,
            video_label=LABELS[item_id] + ' - ' + item.label,
            download_mode=True)

The icon of each channel are 512x512. Can you please adapt it?

Thanks,
Wwark.

**Comment by SylvainCecchetto** [comment]
Hi!

Sorry I just saw this PR. Thank you Gaet81 for your work. I will take a look tonight if I can!

**Comment by wwark** [comment]
Hi,

We changed also the images location, the images are stored in this repository "https://github.com/Catch-up-TV-and-More/images".
the same image are used for the website (https://catch-up-tv-and-more.github.io/channels/), PVR IPTV Simple with m3u file and the plugin.

**Comment by SylvainCecchetto** [comment]
I just tested your PR, thank you for proposing new contents :D 

As wwark I think it would be better to have two separate files because the two channels do not seem to be the same group (unlike France TV or 6play, etc ...).

Regarding the scrrapping to get the categories, I agree that it would be ideal. But at first I do not see any problem on my side to merge the current version.
Just have to separate in two files with a name different from dailymotion.py

What do you think about that @wwark?

**Comment by wwark** [comment]
Hi @SylvainCecchetto,

Your last merge in this PR will have some impact in the history of the commits I think. Maybe we need to redo this PR and close this one.

OK to merge with different names with the same code. We will see in the future to add catergories.

Thanks for the review,
Wwark.

**Comment by SylvainCecchetto** [comment]
Hi!
Oh you think? I thought it would not change much in history xD
I will split in two files, move the images and merge this PR.

**Comment by wwark** [comment]
ok thank you for the merge !

**Comment by Gaet81** [comment]
Merci à vous pour cet add-on et la réactivité!

**Pull request merged**
