### PR TITLE
RTBF hardcode live url if it contains DRM

### PR DESCRIPTION
**Pull request by Gaet81**
Live aren't working anymore because they are passing by an ad service and we can't change the SAMPLE-AES by the AES-128 file...I have hardcoded the URL that is working but I don't know how long it will continue to work.

### CODE REVIEW

**Comment by Gaet81** [comment]
fix issue #526

**Comment by alexbelgium** [comment]
Thanks for working on that! I've exported your forked repo and installed it as an addon but it doesn't seem to work. Here is my log :
```
2021-12-05 12:49:17.933 T:1244     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf/set_live_url/?item_id=tipiktv
2021-12-05 12:49:17.955 T:1592     INFO <general>: initializing python engine.
2021-12-05 12:49:21.649 T:1523     INFO <general>: script.module.metadatautils --> Rate limiter active for themoviedb.org - delaying request with 1 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
2021-12-05 12:49:35.499 T:1592     INFO <general>: CPythonInvoker(42, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2021-12-05 12:49:35.533 T:1594     INFO <general>: initializing python engine.
2021-12-05 12:49:36.399 T:1592     INFO <general>: Python interpreter stopped
2021-12-05 12:49:45.884 T:1569    ERROR <general>: OpenDemuxStream - Error creating demuxer
2021-12-05 12:49:45.884 T:1569     INFO <general>: CVideoPlayer::OnExit()
```

**Comment by alexbelgium** [comment]
Seems to work! I've installed your forked repo as addon to test. I'll test it a bit further. Thanks very much

**Comment by sy6sy2** [comment]
Thank you @Gaet81!

**Comment by dur3x** [comment]
@Gaet81 thanks a lot my friend 🍺

**Pull request merged**
