### PR TITLE
6play improvements

### PR DESCRIPTION
**Pull request by gromez**
- Improve quality for 6play catch-up and live TV
- Increase number of available 6play programs

### CODE REVIEW

**Comment by wwark** [comment]
Thanks a lot @gromez it is a great improvement !

**Comment by wwark** [comment]
Hi @gromez,

On 6Play, there is new channel https://www.6play.fr/cage-warriors
I can't find the name of channel to propose contents.
For the moment, my test returns no content.
Could you please try on android ?

Thanks,

**Comment by wwark** [comment]
Fun Radio and RTL 2 don't have contents also for catchup TV.

**Comment by gromez** [comment]
Hello @wwark 

I tried Cage Warriors on Android, and it's not a new channel, you can find it on W9 > Sport category. It works fine with your plugin too.

I did some tests for Fun Radio, and I think it will need some changes.
First, videos must be retrieve with _android_ endpoint, not _chromecast_ one: https://android.middleware.6play.fr/6play/v2/platforms/m6group_androidmob/services/6play/programs/7814/videos?offset=0&limit=20&type=vc%2Cvi%2Cplaylist&subcat=8238&sort=subcat&csa=6&with=clips%2Ctags%2Cfreemiumpacks%2Cextra_data
So I think URL_VIDEOS and URL_VIDEOS can be edited, there is no major issue, even for other channels.

For Fun Radio, I think it's a new _type_ that is not yet managed on the plugin: _usp_hls_h264_ (there is an example on the bottom URL). It must be the same issue for RTL 2.
I will check later today if I can fix this problem.

**Comment by gromez** [comment]
Sorry for Cage Warriors, there was a new channel (that must be just a redirect): https://android.middleware.6play.fr/6play/v2/platforms/m6group_androidmob/services/courses/meas
So, the name for this category is _courses_ and folders can be retrieved here: http://android.middleware.6play.fr/6play/v2/platforms/m6group_androidmob/services/courses/folders?limit=999&offset=0

**Comment by wwark** [comment]
Thank you 'courses' works !

**Pull request merged**
