### PR TITLE
[Project] PR workflow: flake8 with forks

### PR DESCRIPTION
**Pull request by darodi**
[Project] pr workflow: flake8 with forks

### CODE REVIEW

**Comment by darodi** [comment]
flake works on PR from a a fork with this change.
but we get an error later

image

**Comment by darodi** [comment]
fixed test-plugin-modules job

**Comment by darodi** [comment]
solution à la discussion dans #659

**Comment by joaopa00** [comment]
Looks OK to me. Can you only change the title of the patch in [Project] PR workflow: flake8 with forks - fix test-plugin-modules
Thanks you for the work.

**Comment by darodi** [comment]
done

mycanal flake8 fails... it's from another commit in dev

**Pull request merged**
