### PR TITLE
Add live for RTLplay Channels

### PR DESCRIPTION
**Pull request by Gaet81**
I added the live for RTL and updated the tv guide

### CODE REVIEW

**Comment by wwark** [comment]
Thank You @Gaet81.

I don't manage to make it work on my side. I will test it.

Thanks again.

**Comment by Forage** [comment]
I'm a bit surprised you merged it in this state @wwark, it messed up the commit history quite a bit. I suppose a rebase should have been done on @Gaet81's side instead of a merge.

**Comment by wwark** [comment]
Hi @Forage,
Ok sorry I didn't think about history I will be more vigilant in the future.
Do you know how we can fix the history? maybe we can revert to the lastest commits and add again this PR?

**Comment by Forage** [comment]
I think the only way to fix it will get messy as well, since you already added two additional changes, but if you think it's worth it:

1. Pull dev locally
2. Delete dev on GitHub
3. Branch locally from commit 55cb5ee
4. Push new branch to/as dev on GitHub
5. Cherry pick your 6d7d634 and efe5968 again
6. Clean up this PR before reapplying it.

I can't predict how happy GitHub will be with all this in terms of PR's and stuff.
The risk, though maybe not that big: others might have pulled dev already, leaving them with the mess to clean up later when they decide to provide fixes.

**Comment by wwark** [comment]
Maybe I can use:
git revert HEAD~2..HEAD # To remove my last 2 commits 
https://help.github.com/en/articles/reverting-a-pull-request # To revert the last PR and asked a rebase in the new PR.

What do you think?

Thanks,
Wwark

**Comment by Forage** [comment]
The revert will create a new commit again, essentially keeping the mess.
I don't think you can push anything you did locally to remove certain commits from history without replacing the dev branch on GitHub. It will refuse to push it.

**Comment by Forage** [comment]
Ah, I now see the GitHub article to undo a PR. I never used it, maybe it'll do the trick.

**Comment by Gaet81** [comment]
Hi,

Sorry to have cause you issues...yes, as @Forage said I've done a rebase rather than a merge...obviously I shouldn't have done so :(

@wwark what is your issue? A good test to see if it's what I added that is causing issue is to try a replay video. if it's not working then it should not be my code...

**Comment by Gaet81** [comment]
@wwark please note as well that if you tried rtl info or rtl sport..these are webchannel and so not always active. so if you clicking on those 2 channels if nothing is currently showing it just means that there is no stream.

**Comment by Forage** [comment]
A rebase would have been just fine, if done in the right direction ;)
It looks like you rebased the dev branch instead of your feature branch.

No harm done this time. It's limited to a small set of commits and it just looks a bit messy. Cleaning it up now isn't essential, but a good exercise nevertheless ;P
Just make sure you're PR only includes commits you actually made next time.

As for temporary available channels, would it be possible to check whether they are up and display a clean message if not?

**Comment by wwark** [comment]
Hi @Gaet81,
Sorry what I want to say is I tried to implement the live tv for RTLPlay but not managed to make it work.
I'm happy you find the way :+1: 
I will try to return to the commit before the merge to be able to do the rebase.

Yes you can add a check if the stream is available or not and send a notification (used the label below)
msgctxt "#30716"
msgid "Video stream is not available"
msgstr ""

Thanks,
Wwark.

**Comment by wwark** [comment]
I tried to revert the PR but it created a new PR so not good for the history I think...
I prefered to let at it not to make more problem in the history ...
In the future I will ask for rebase.

Thanks for your help !

**Comment by Gaet81** [comment]
Arf, really sorry about this. I should install git desktop will be easier. I hope my new pull request is better.

And concerning your trial to make rtl live work...you had done already most of the job, took the live from M6 and compare it to the video function then make some changes. so thank you for all your good prep ;)

**Pull request merged**
