### PR TITLE
Use more details for France-*

### PR DESCRIPTION
**Pull request by Forage**
Plenty of details are available in the JSON we already request. So without an additional load, we can provide much more info in the details of each broadcast.

Details in particular:
- cast and roles, considering the presenter as part of the cast
- rating
- season and episode
- director

In the same go I tried to reduce duplicate code a bit by putting the common part of `list_videos` and `list_videos_last` into a separate function.

With season and episode in place we have a way to distinguish the different episodes, where often programs display the identical broadcast dates or nothing at all. The added bonus is that you can sort the video list by episode(/season) now.
The interesting bit is where `item.info['mediatype'] = "episode"` is being applied now. This is needed to not have those number be treated as totals in the video's details but have them properly displayed at the top underneath the title.

Before, the `presenter` was displayed as `director`, and only for the search results. I changed this to it being a cast member, consistently applying it to list_videos as well. This would be more correct than it being mislabelled `director` due to lack of proper `presenter` support in Kodi.

### CODE REVIEW

**Comment by wwark** [comment]
Hi Forage,

Thank you for this new contribution.
I have some questions related to mediatype in list_programs and list_videos.

In list_programs, you add "item.info['mediatype'] = "tvshow"" I think it is not a good idea because of three points:
- Some programs are not TVShow

- It can add more support if the person chooses something different "All videos" in the configuration option like below I choose watch and 0 programs appeared
screenshot from 2018-12-15 09-31-03

- the icon of the screenshot means it is the content but it is not the case.
screenshot from 2018-12-15 09-30-00

In the plugin, we remove all item.info['mediatype'] because it is difficult to know the content (movies, tvshows, etc....), also for the configuration to choose to display contents (All videos, Watched, unwatched) we have several questions in the forum regarding person search the content not appeared.
Not set item.info['mediatype'] keep the same layout for all replay

If we removed the both item.info['mediatype'] what is the impact on your adding details?

I have also this error when I tried to play the "20 heures" of France 2 the value of id_diffusion is not OK.
`09:42:08.542 T:140632181614336   FATAL: [Catch-up-TV-&-More.support] get_video_url() got an unexpected keyword argument 'id_diffusion'
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 282, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                            TypeError: get_video_url() got an unexpected keyword argument 'id_diffusion'
09:42:08.542 T:140632181614336 WARNING: ###### debug ######
09:42:08.542 T:140632181614336 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/francetv/get_video_url/'
09:42:08.542 T:140632181614336 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'france-2', 'item_dict': {u'info': {'aired': u'2018-12-03', 'title': u'\xc9dition du lundi 3 d\xe9cembre 2018', u'mpaa': u'TP', u'tvshowtitle': u'Journal 20h00', u'cast': [u'Anne-Sophie Lapix'], 'year': u'2018', 'date': u'03.12.2018', u'duration': 2258}, u'art': {u'fanart': u'http://api-front.yatta.francetv.fr/image/vignette_16x9/1024/576/0/b/0/4a27cd62-877d71c7fd6745da810c7a1560183d5c5c28b2e0ee62cb42502c8f24093bb0b0.jpg', u'thumb': u'http://api-front.yatta.francetv.fr/image/vignette_16x9/1024/576/0/b/0/4a27cd62-877d71c7fd6745da810c7a1560183d5c5c28b2e0ee62cb42502c8f24093bb0b0.jpg'}, u'stream': {}, u'label': u'\xc9dition du lundi 3 d\xe9cembre 2018', u'params': <class 'codequick.listing.Params'>({'item_id': u'france-2', '_title_': u'\xc9dition du lundi 3 d\xe9cembre 2018', 'item_dict': {...}, 'id_diffusion': u'a2ce0353-4e54-41ec-8d60-d29a3a32e095'}), u'context': {u'Download': 'XBMC.RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158080000006672616e63652d327102550d646f776e6c6f61645f6d6f6465710388550b766964656f5f6c6162656c7104582d0000004672616e63652032202d20c389646974696f6e206475206c756e646920332064c3a963656d62726520323031387105550c69645f646966667573696f6e7106582400000061326365303335332d346535342d343165632d386436302d6432396133613332653039357107752e)'}, u'property': <class 'codequick.listing.Property'>({})}, 'id_diffusion': u'a2ce0353-4e54-41ec-8d60-d29a3a32e095'}'`

Thanks again for your return,
Wwark

**Comment by Forage** [comment]
`item.info['mediatype'] = "tvshow"` can be removed as far as I can tell. `item.info['mediatype'] = "episode"` is needed on the other hand. It prevents issues like https://github.com/willforde/script.module.codequick/issues/21
I will check if not setting that value will have a bigger impact on the list view as well.

Play/played indications worked for me. Is this what you are missing?

I'll try to reproduce your error but it's strange thatI haven't seen it before. Which version of Kodi and Codequick are you using?

**Comment by wwark** [comment]
I used Kodi 18 rc2 with this version of codequick https://mirrors.kodi.tv/addons/krypton/script.module.codequick/script.module.codequick-0.9.7.zip

I will try to find the cause also.

Can you please update this PR to remove item.info['mediatype'] = "tvshow"?

Thanks,
Wwark

**Comment by wwark** [comment]
I remove item.info['mediatype'] = "tvshow"
I replace in get_video_url all broadcast_id by id_diffusion and it fixed my issue.
Can you please update the PR to be able to merge it ?

Thanks,
Wwark

**Comment by Forage** [comment]
That's the first time I've seen an empty rating. Fixed now

**Comment by Forage** [comment]
Fixed, sorry, I was in a hurry earlier

**Comment by wwark** [comment]
Thanks a lot for this contribution !

**Pull request merged**
