### PR TITLE
Add Flemish regional live channels

### PR DESCRIPTION
**Pull request by dagwieers**
This adds Flemish regional live channels.

This relates to Catch-up-TV-and-More/resource.images.catchuptvandmore#1

### CODE REVIEW

**Comment by wwark** [comment]
Hi @dagwieers,
Thank you for this PR but we can't merge this PR at this state because it will be reject on the official repo of Kodi when we proposed those changes.

If you check the code on other channels py you will see we connect to the channel to official url ou official api (if mobile or application) and we try to retrieve the content (live tv or catchup tv)

So if we take Bruzz TV for example,
We connect to "https://www.bruzz.be/live#watch" and we tried to retrieve the m3u8 and we propose it to the Kodi player.

The code can be,
resp = urlquick.get('https://www.bruzz.be/live#watch', max_age=-1)
# TODO to get the m3u8
return url_m3u8

I will check tonight if I found a solution for bruzz and explain how I manage to add it.

Thanks,

**Comment by dagwieers** [comment]
All these live tv channels are already as-is in the Regio TV add-on which was accepted fine in the Kodi repository.

So I don't think scraping is a necessity at all. IMO it is a liability. If the HTML code changes, the stream will stop working. These streams have been proven to be stable the past year.

**Comment by wwark** [comment]
Thanks for those informations.
We will check the kodi team.
I let this PR opened

**Comment by dagwieers** [comment]
@wwark Honestly, I think a combination of what your are doing and hardcoded URLs is probably preferably. If the parsing fails, a fallback to a hardcoded URL is probably better in all cases. If you also report that the parsing failed (but playback still works) we have the ability to fix the parsing without impacting the user.

Likewise, hardcoded URLs _and_ parsing can be tested by a GitHub CI action that is e.g. run hourly or daily. We do this for our add-ons as well to ensure that changes to the back-end are found before they impact users. See: https://github.com/add-ons/plugin.video.vrt.nu/actions?query=workflow:Status

**Comment by dagwieers** [comment]
BTW If IPTV Manager support is added to Catch-up TV & More, and some of the functionality of Regio TV is added as well (plot and URL for static live streams, better referer support, etc.), and this PR would be merged (with parsing support too), I don't see a good reason to keep the Regio TV around.

And our (Flemish) community would be more actively participating with Catch-up TV & More, also for VOD support. This would be a win-win.

**Comment by dagwieers** [comment]
In the case of BRUZZ, de parser would need to extract specific JavaScript from this block:
```javascript
<script type="text/javascript">
    window.livePage = {
        'radioStream': 'https://rrr.sz.xlcdn.com/?account=fmbrussel&file=fmb988.mp3&type=live&service=icecast&protocol=https&port=8000&output=pls',
        'videoIframe': '<iframe width="100%" height="350" src="//player.cdn01.rambla.be?account_id=WXv1JD&amp;event_id=V3n5YY" frameBorder="0" style="border: 0" allow="autoplay; fullscreen" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>',
        'radioLinks': '[{"url":"\/contacteer-de-radiostudio","urlAbsolute":"https:\/\/www.bruzz.be\/contacteer-de-radiostudio","text":"Contacteer de radiostudio","external":false,"target":"_self"},{"url":"\/radio","urlAbsolute":"\/radio","text":"Programmaschema BRUZZ radio","external":false,"target":"_self"}]',
        'videoLinks': '[{"url":"\/video","urlAbsolute":"https:\/\/www.bruzz.be\/video","text":"Bekijk alle video&apos;s","external":false,"target":"_self"},{"url":"","urlAbsolute":"","text":"","external":false,"target":"_self"}]'
    };
</script>
```

So it's not that easy.

**Comment by wwark** [comment]
Yes sometimes it is not easy to find where the live tv stream is present.
We have confirmation it is not a problem with kodi Team to put directly the stream on the code.
 Could you please redo the PR because you have previous commit on this PR and we will lost history if I merged it like that.
image

Thanks again for this PR.

**Comment by dagwieers** [comment]
> Could you please redo the PR because you have previous commit on this PR and we will lost history if I merged it like that.

Rebased.

**Comment by wwark** [comment]
Thanks for the rebase.

**Pull request merged**
